package io.liulx.dianping.model;

import java.util.Date;

public class UserModel {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_user.id
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_user.created_at
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  private Date createdAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_user.updated_at
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  private Date updatedAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_user.telphone
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  private String telphone;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_user.password
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  private String password;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_user.nick_name
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  private String nickName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_user.gender
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  private Integer gender;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_user.id
   *
   * @return the value of t_user.id
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_user.id
   *
   * @param id the value for t_user.id
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_user.created_at
   *
   * @return the value of t_user.created_at
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public Date getCreatedAt() {
    return createdAt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_user.created_at
   *
   * @param createdAt the value for t_user.created_at
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_user.updated_at
   *
   * @return the value of t_user.updated_at
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public Date getUpdatedAt() {
    return updatedAt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_user.updated_at
   *
   * @param updatedAt the value for t_user.updated_at
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_user.telphone
   *
   * @return the value of t_user.telphone
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public String getTelphone() {
    return telphone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_user.telphone
   *
   * @param telphone the value for t_user.telphone
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public void setTelphone(String telphone) {
    this.telphone = telphone == null ? null : telphone.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_user.password
   *
   * @return the value of t_user.password
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_user.password
   *
   * @param password the value for t_user.password
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_user.nick_name
   *
   * @return the value of t_user.nick_name
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public String getNickName() {
    return nickName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_user.nick_name
   *
   * @param nickName the value for t_user.nick_name
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public void setNickName(String nickName) {
    this.nickName = nickName == null ? null : nickName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_user.gender
   *
   * @return the value of t_user.gender
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public Integer getGender() {
    return gender;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_user.gender
   *
   * @param gender the value for t_user.gender
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  public void setGender(Integer gender) {
    this.gender = gender;
  }
}