package io.liulx.dianping.dal;

import io.liulx.dianping.model.UserModel;

public interface UserModelMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  int insert(UserModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  int insertSelective(UserModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  UserModel selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  int updateByPrimaryKeySelective(UserModel record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_user
   *
   * @mbg.generated Wed Dec 18 22:07:40 CST 2019
   */
  int updateByPrimaryKey(UserModel record);
}