package io.liulx.dianping.dal;

import io.liulx.dianping.model.UserModel;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_user
     *
     * @mbg.generated Wed Dec 25 21:13:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_user
     *
     * @mbg.generated Wed Dec 25 21:13:53 CST 2019
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_user
     *
     * @mbg.generated Wed Dec 25 21:13:53 CST 2019
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_user
     *
     * @mbg.generated Wed Dec 25 21:13:53 CST 2019
     */
    UserModel selectByPrimaryKey(Integer id);

    UserModel selectByTelephone(@Param("telephone") String telephone);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_user
     *
     * @mbg.generated Wed Dec 25 21:13:53 CST 2019
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * t_user
     *
     * @mbg.generated Wed Dec 25 21:13:53 CST 2019
     */
    int updateByPrimaryKey(UserModel record);
}